### ISSUE TITLE
Improve the "Event Calendar" experience

### ISSUE THREAD

**Issue by payne911** [cscareerhub/csch-web#35]
List of suggestions:

1. Add meta-data timestamp on each event so that they can automatically be rendered as being "upcoming" or "past" events.
2. There should be a way to link events with their respective "video + transcript blog post".
3. In one way or another, there should be a list of the questions which actually were answered during the session, ideally with a YouTube timestamp for each.

Unfortunately, while I believe the 3rd point would be quite beneficial, I'm really not sure how that could easily be automated as much as possible.

**Comment by brendacs** [comment]
Another one: auto-generate the event calendar from the individual event calendar pages

**Comment by brendacs** [comment]
Noting that items 1 and 2 here were handled (but manually) by https://github.com/cscareerhub/csch-web/commit/67e52425ae9107206ac2d006196d2a9de83f1651. Will still need to automate these features.
