### ISSUE TITLE
Add link to YouTube channel on the website

### ISSUE THREAD

**Issue by RogueArt** [cscareerhub/csch-web#39]
Since we have a YouTube channel with recordings of the events, we should link the channel on the row of icons on the bottom. It'd fit nicely with the Discord and Reddit icons at the bottom.

![image](https://user-images.githubusercontent.com/57082175/127588159-ae6e451c-581c-42f4-b972-e3b95d8cffc7.png)

If we want to do something with the YouTube API so that the recordings automatically get linked to the main website, I can open another issue for that and I'd like that assigned to me if possible.

**Comment by sif** [comment]
This is a good idea. I'll hunt around for a logo we can use unless we have one in the back already?
