### ISSUE TITLE
Align buttons

### ISSUE THREAD

**Issue by payne911** [cscareerhub/csch-web#41]
This is minor, and potentially only bothers me, but:

![image](https://user-images.githubusercontent.com/38117856/129429436-a9b8f9e6-69f1-4d8b-93b2-eafdf03f7e78.png)

I feel like the buttons should all be aligned at the button?

Something is tingling my OCD.

**Comment by sif** [comment]
If I understand correctly, you wish to see the buttons all at the same location at the bottom left (or some other position) rather than have it based on the paragraph size?

**Comment by brendacs** [comment]
Resolved by https://github.com/cscareerhub/csch-web/pull/43
