### ISSUE TITLE
Make infoBox background darker

### ISSUE THREAD

**Issue by RogueArt** [cscareerhub/csch-web#42]
Currently the info boxes have the same background color as the parent so it blends into it at the top:
![image](https://user-images.githubusercontent.com/57082175/129430244-bd66d2de-816d-473a-9b04-921200a65b41.png)

We can change the color of `.InfoBox__infoBox` from `$discord-med-dark` to `$discord-lighter` to avoid this and give the box more contrast.
![image](https://user-images.githubusercontent.com/57082175/129430277-90b42dd3-466a-42e1-85bc-bf689e81cd90.png)

**Comment by brendacs** [comment]
Consider darkening the background behind the boxes instead

<img width="1438" alt="Screen Shot 2021-08-14 at 12 13 11 PM" src="https://user-images.githubusercontent.com/18357096/129457852-16e78b57-1efb-4b02-a68c-2ed2d3e8a37c.png">

**Comment by RogueArt** [comment]
Oh yeah, that definitely looks a lot nicer!
